name: Bug Report
description: File a bug report to help us improve the DataHUB(s)
title: "[Bug]: "
labels: ["Type: Bug :bug:"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give us a step by step what you did.
      placeholder: Tell us what happened! If possible, please include error messages or screenshots to describe the issue.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect?
      description: This field might be optional depending on the bug you encountered.
      placeholder: Tell us what you wanted to see! 
  - type: dropdown
    id: datahub-host
    attributes:
      label: DataHUB Host
      description: Which DataHUB do you use?
      options:
        - git.nfdi4plants.org
        - gitdev.nfdi4plants.org
        - gitlab.nfdi4plants.de
        - gitlab.plantmicrobe.de
        - datahub.rz.rptu.de
        - datahubdev.hhu.de
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser do you use?
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Opera
        - other
